
export interface PersonalInfo {
  profilePic: string;
  fullName: string;
  jobTitle: string;
  summary: string;
  email: string;
  phone: string;
  address: string;
  linkedin: string;
  website: string;
}

export interface Education {
  id: number;
  degree: string;
  institution: string;
  startDate: string;
  endDate: string;
  current: boolean;
  description: string;
}

export interface Experience {
  id: number;
  title: string;
  company: string;
  startDate: string;
  endDate: string;
  current: boolean;
  description: string;
}

export interface Project {
  id: number;
  name: string;
  tech: string;
  url: string;
  description: string;
}

export interface Skills {
  tech: string;
  soft: string;
  languages: string;
  certifications: string;
}

export interface AdditionalInfo {
  hobbies: string;
  volunteer: string;
  references: string;
}

export interface ResumeData {
  personal: PersonalInfo;
  education: Education[];
  experience: Experience[];
  projects: Project[];
  skills: Skills;
  additional: AdditionalInfo;
}

export interface ResumePlan {
  // FIX: Added 'summary' to the sections type to allow it as a valid section from the AI plan.
  sections: (keyof Omit<ResumeData, 'additional' | 'personal'> | 'summary')[]; // Order of sections
  ai_suggestions: {
    [key: string]: string; // AI tips for each section
  };
  // FIX: Removed properties not generated by the AI to prevent runtime errors.
}


// Extend the Window interface for external libraries loaded via script tags
declare global {
  interface Window {
    jspdf: any;
    html2canvas: any;
    SpeechRecognition: any;
    webkitSpeechRecognition: any;
  }
}
